### ISSUE TITLE
Locale and GDOM

### ISSUE THREAD

**Issue by dargmuesli** [kmein/menstruation#1]
https://github.com/kmein/menstruation/blob/0e50e91fa59fcec9f9dd8674c7cf56880f67d53a/frontend.py#L8 is an issue for me. `de_DE.UTF-8` works for me though. Pull request?

GDOM complains about not finding module `schema`. Changing https://github.com/syrusakbary/gdom/blob/f832c915f8cc39510f5bc734a2665715acbc747b/gdom/cmd.py#L9 to `from .schema import schema` (inserting the dot) fixes that. Do you know why? A Python 2/3 problem?

**Comment by kmein** [comment]
Yeah you can PR the locale thing. No idea why that works for me, didn't even look that up :no_mouth: 

I guess that's GDOM's problem. Also I've never seen the `import .module` syntax. And to top it all of, I have no idea how to get this to work without changing shit upstream.

P.S. How'd you find out about that dot-import thing?

**Comment by dargmuesli** [comment]
I looked into the next package in the venv directory that was installed (`flask_graphql`) and in `blueprint.py` it said `from .graphqlview import GraphQLView`.

**Comment by kmein** [comment]
Btw don't PR. Fixed it myself :3

**Comment by dargmuesli** [comment]
Dann push auch 🤣

**Comment by kmein** [comment]
Ist gepusht auf mock. Solange GDOM nicht geht mach ich mit dem master nix. :D

**Comment by dargmuesli** [comment]
Ach ja, ich Nudel muss ja auch remotes adden.
